#!/usr/bin/env bash
# Attempt 9 (v12 fidelity-motion) — LEG-FIDELITY fix on the WARM v10 box. Native tempo.
#
# v11 = v10 + a dedicated leg-tracking reward + softened stance/drift so the
# lower body stops losing to the arms (v10 rollout: legs 43-59% vs arms 77-137%
# of the reference amplitude in the arm-swing section — a reward asymmetry, not a
# capability limit). See cloud/sim2real_task_v11.py header.
#
# Reuses the tempo npz already generated by run_attempt7 (thriller_v12_0*.npz —
# the motion is identical, only the reward changes), so NO retiming/convert step.
#
# Push first (laptop):
#   scp -P <PORT> -i .secrets/greennode_rsa cloud/{sim2real_task_v11.py,\
#     train_v11_curriculum.sh,run_attempt9.sh} root@<IP>:/workspace/notebook-data/cloud/
# Then on the box:
#   export G1_GATE_ANKLE_P95_NOMINAL_NM=22 G1_GATE_ANKLE_P95_WORST_NM=25
#   cd /workspace/notebook-data && nohup bash cloud/run_attempt9.sh > attempt9.out 2>&1 &
#
# $$$ Box already billing since the v10 run — this reuses it. Pull + DELETE after.
set -uo pipefail
NB=${NB:-/workspace/notebook-data}
PY=$NB/envs/mjlab/bin/python
CSV=${G1_MOTION_CSV:-$NB/motions/thriller_v12_full.csv}
CSV2NPZ=$NB/repos/mjlab/src/mjlab/scripts/csv_to_npz.py
[ -f "$NB/.wandb_key" ] && export WANDB_API_KEY=$(tr -d '[:space:]' < "$NB/.wandb_key")

cd "$NB"
say() { echo "== $* == $(date -Is)"; }
die() { echo "!! $*"; exit 1; }

nvidia-smi --query-gpu=utilization.gpu --format=csv,noheader >/dev/null || die "no GPU"

# Tempo npz: reuse if a prior attempt already made them; else retime from the
# beatsync CSV (fresh box). Same 4 variants v10 used — identical motion, v11
# only changes the reward, so the npz are shared.
declare -A SPEED=( [060]=0.60 [075]=0.75 [090]=0.90 [100]=1.00 )
if [ ! -f "$NB/motions/thriller_v12_100.npz" ]; then
  [ -f "$CSV" ] || die "motion CSV missing: $CSV — push it from the laptop"
  head -1 "$CSV" | awk -F, 'NF != 36 { exit 1 }' || die "CSV not 36-column"
  say "retime tempo variants (fresh box: 0.60/0.75/0.90/1.00 from $CSV)"
  for k in 060 075 090 100; do
    OUT=$NB/motions/thriller_v12_${k}.csv
    [ -f "$OUT" ] || "$PY" "$NB/cloud/retime_motion.py" --input "$CSV" --output "$OUT" \
        --speed "${SPEED[$k]}" --check-json "$NB/motions/thriller_v12_${k}_check.json" \
      || die "retime ${SPEED[$k]}x FAILED"
    NPZ=$NB/motions/thriller_v12_${k}.npz
    if [ ! -f "$NPZ" ]; then
      MUJOCO_GL=egl "$PY" "$CSV2NPZ" --input-file "$OUT" \
          --output-name "thriller_v12_${k}" --input-fps 30 --output-fps 50 || true
      [ -f /tmp/motion.npz ] && cp /tmp/motion.npz "$NPZ"
    fi
    [ -f "$NPZ" ] || die "npz absent after conversion: $NPZ"
    echo "  thriller_v12_${k}.npz ready"
  done
fi
say "preflight OK (tempo npz present)"
for k in 060 075 090 100; do
  [ -f "$NB/motions/thriller_v12_${k}.npz" ] || die "missing thriller_v12_${k}.npz"
done

say "selfcheck (v11 task, stage-1 clock 0.60x -> G1_SLOWDOWN=1.6667)"
G1_SLOWDOWN=1.6667 G1_OBS_HISTORY=5 G1_PHASE_OBS=${G1_PHASE_OBS:-0} \
  "$PY" "$NB/cloud/sim2real_task_v11.py" --selfcheck || die "selfcheck FAIL"

say "64-env GPU smoke test (v11, stage-1 conditions, 3 iters)"
G1_SLOWDOWN=1.6667 G1_OBS_HISTORY=5 G1_PHASE_OBS=${G1_PHASE_OBS:-0} \
G1_CMD_DELAY_MAX_LAG=4 G1_OBS_DELAY_MAX_LAG=1 G1_DRIFT_TERM_M=0.8 \
  "$PY" "$NB/cloud/sim2real_task_v11.py" Mjlab-Tracking-Flat-Unitree-G1-S2R-V11 \
    --env.scene.num-envs 64 --env.commands.motion.motion-file "$NB/motions/thriller_v12_060.npz" \
    --agent.max-iterations 3 --agent.run-name smoketest-v12 || die "smoke test FAIL"

say "LAUNCH v12 = v11 recipe on the FIDELITY motion (full intro, unwarped, guard-cleaned)"
export G1_WAIST_SRC_WINDOWS="15.5-20.5,27.5-38.5"   # +2.5s: v12 restores the intro
export RUN_NAME=train-thriller_v12fid-$(date +%m%d)
M060=$NB/motions/thriller_v12_060.npz \
M075=$NB/motions/thriller_v12_075.npz \
M090=$NB/motions/thriller_v12_090.npz \
M100=$NB/motions/thriller_v12_100.npz \
  bash "$NB/cloud/train_v11_curriculum.sh"
say "run_attempt9 DONE — pull exports, judge vs calibrated bars, sign, DELETE THE BOX"
