#!/usr/bin/env bash
# Attempt 8 (v11) — LEG-FIDELITY fix on the WARM v10 box. Native tempo.
#
# v11 = v10 + a dedicated leg-tracking reward + softened stance/drift so the
# lower body stops losing to the arms (v10 rollout: legs 43-59% vs arms 77-137%
# of the reference amplitude in the arm-swing section — a reward asymmetry, not a
# capability limit). See cloud/sim2real_task_v11.py header.
#
# Reuses the tempo npz already generated by run_attempt7 (thriller_v10_0*.npz —
# the motion is identical, only the reward changes), so NO retiming/convert step.
#
# Push first (laptop):
#   scp -P <PORT> -i .secrets/greennode_rsa cloud/{sim2real_task_v11.py,\
#     train_v11_curriculum.sh,run_attempt8.sh} root@<IP>:/workspace/notebook-data/cloud/
# Then on the box:
#   export G1_GATE_ANKLE_P95_NOMINAL_NM=22 G1_GATE_ANKLE_P95_WORST_NM=25
#   cd /workspace/notebook-data && nohup bash cloud/run_attempt8.sh > attempt8.out 2>&1 &
#
# $$$ Box already billing since the v10 run — this reuses it. Pull + DELETE after.
set -uo pipefail
NB=${NB:-/workspace/notebook-data}
PY=$NB/envs/mjlab/bin/python
[ -f "$NB/.wandb_key" ] && export WANDB_API_KEY=$(tr -d '[:space:]' < "$NB/.wandb_key")

cd "$NB"
say() { echo "== $* == $(date -Is)"; }
die() { echo "!! $*"; exit 1; }

say "preflight (reuse v10 tempo npz)"
for k in 060 075 090 100; do
  [ -f "$NB/motions/thriller_v10_${k}.npz" ] || die "missing thriller_v10_${k}.npz — run attempt7 retime first"
done
nvidia-smi --query-gpu=utilization.gpu --format=csv,noheader >/dev/null || die "no GPU"

say "selfcheck (v11 task, stage-1 clock 0.60x -> G1_SLOWDOWN=1.6667)"
G1_SLOWDOWN=1.6667 G1_OBS_HISTORY=5 G1_PHASE_OBS=${G1_PHASE_OBS:-0} \
  "$PY" "$NB/cloud/sim2real_task_v11.py" --selfcheck || die "selfcheck FAIL"

say "64-env GPU smoke test (v11, stage-1 conditions, 3 iters)"
G1_SLOWDOWN=1.6667 G1_OBS_HISTORY=5 G1_PHASE_OBS=${G1_PHASE_OBS:-0} \
G1_CMD_DELAY_MAX_LAG=4 G1_OBS_DELAY_MAX_LAG=1 G1_DRIFT_TERM_M=0.8 \
  "$PY" "$NB/cloud/sim2real_task_v11.py" Mjlab-Tracking-Flat-Unitree-G1-S2R-V11 \
    --env.scene.num-envs 64 --env.commands.motion.motion-file "$NB/motions/thriller_v10_060.npz" \
    --agent.max-iterations 3 --agent.run-name smoketest-v11 || die "smoke test FAIL"

say "LAUNCH v11 leg-fidelity curriculum"
M060=$NB/motions/thriller_v10_060.npz \
M075=$NB/motions/thriller_v10_075.npz \
M090=$NB/motions/thriller_v10_090.npz \
M100=$NB/motions/thriller_v10_100.npz \
  bash "$NB/cloud/train_v11_curriculum.sh"
say "run_attempt8 DONE — pull exports, judge vs calibrated bars, sign, DELETE THE BOX"
